image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info

test:2.7:
  stage: test
  script:
  - cp Dockerfile.Python2.7 Dockerfile
  - docker build -t pytest-image .
  - docker run pytest-image /usr/local/bin/python -m pytest --cov=/home/etude /home/etude/tests
