image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info

test:python3.7:
  stage: test
  script:
  - cp Dockerfile.python3.7 Dockerfile
  - docker build -t pytest-image .
  - docker run pytest-image /usr/local/bin/python -m pytest --cov=/home/etude /home/etude/tests

test:python2.7:
  stage: test
  script:
  - cp Dockerfile.python2.7 Dockerfile
  - docker build -t pytest-image .
  - docker run pytest-image /usr/local/bin/python -m pytest --cov=/home/etude /home/etude/tests

test:python3.6.8:
  stage: test
  script:
  - cp tests/Dockerfile_templates/Dockerfile.python3.6.8 Dockerfile
  - docker build -t pytest-image .
  - docker run pytest-image /usr/local/bin/python -m pytest --cov=/home/etude /home/etude/tests

test:python3.5.3:
  stage: test
  allow_failure: true
  script:
  - cp Dockerfile.python3.5.3 Dockerfile
  - docker build -t pytest-image .
  - docker run pytest-image /usr/local/bin/python -m pytest --cov=/home/etude /home/etude/tests


